# Web server settings -
http:

# To make OAuth work on localhost redirect port 80 to port 9090
#sudo iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports 9090
#  if its something you want to do when not on localhost   http://serverfault.com/questions/211536/iptables-port-redirect-not-working-for-localhost
#iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 9090

  port: 9090
  adminPort: 9091
cookiePassword: "thisisasecretkey"
cookieSalt: "ReallySecurecCokkieS£altLikeUhveNoeAIdeAf"
#database:
#  # the name of your JDBC driver
#  driverClass: com.mysql.jdbc.Driver
#  # the username
#  user: root
#  # the password
#  password: ""
#  # the JDBC URL
#  url: jdbc:mysql://localhost:3306/portfolio?zeroDateTimeBehavior=convertToNull
#  # any properties specific to your JDBC driver:
#  properties:
#    charSet: UTF-8
#  # the maximum amount of time to wait on an empty pool before throwing an exception
#  maxWaitForConnection: 1s
#  # the SQL query to run when validating a connection's liveness
#  validationQuery: "/* MyService Health Check */ SELECT 1"
#  # the minimum number of connections to keep open
#  minSize: 8
#  # the maximum number of connections to keep open
#  maxSize: 32
#  # whether or not idle connections should be validated
#  checkConnectionWhileIdle: false
#  # how long a connection must be held before it can be validated
#  checkConnectionHealthWhenIdleFor: 10s
#  # the maximum lifetime of an idle connection
#  closeConnectionIfIdleFor: 1 minute